<?php

namespace Tests\Unit\Models;

use App\Models\Traits\UploadFiles;
use App\Models\Video;
use App\Models\Traits\Uuid;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;

class VideoUnitTest extends TestCase
{
	//use DatabaseMigrations;

	private $video;

	public static function setUpBeforeClass(
	)/* The :void return type declaration that should be here would cause a BC issue */ {
		parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
	}


	protected function setUp(): void {
		parent::setUp();
		$this->video = new Video();
	}

	protected function tearDown(): void {
		parent::tearDown(); // TODO: Change the autogenerated stub
	}

	public static function tearDownAfterClass(
	)/* The :void return type declaration that should be here would cause a BC issue */ {
		parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
	}


	/**
     * A basic unit test example.
     *
     * @return void
     */
    public function testFillableAttribute()
    {
    	$fillable = ['title', 'description', 'year_launched', 'opened', 'rating', 'duration'];
        $this->assertEquals( $fillable, $this->video->getFillable());
    }

    public function testIfUseTraits()
    {
    	$traits = [
    		SoftDeletes::class, Uuid::class, UploadFiles::class
	    ];
    	$videoTraits = array_keys(class_uses(Video::class));
    	$this->assertEquals($traits, $videoTraits);
    }

    public function testCatsAttribute()
    {
    	$casts = ['id' => 'string', 'opened' => 'boolean', 'year_launched' => 'integer', 'duration' => 'integer'];
	    $this->assertEquals($casts, $this->video->getCasts());
    }

	public function testIncrementingAttribute()
	{
		$video = new Video();
		$this->assertFalse($video->incrementing);
	}

	public function testDatesAttribute()
	{
		$dates = ['deleted_at', 'created_at', 'updated_at'];
		foreach ($dates as $date) {
			$this->assertContains($date, $this->video->getDates());
		}
		$this->assertCount(count($dates), $this->video->getDates());
	}
}
